# build stage
FROM node:20.12-alpine3.19 as build
WORKDIR /app
COPY package*.json ./
RUN npm install && \
    npm install -g http-server
COPY . .
RUN npm run build

# output stage
FROM nginx:stable-alpine3.17-slim
# 拷貝必要的檔案即可
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
